name: rxn_yield_context

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.7
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pandas-flavor>=0.2.0
  - pip>=20.0.2
  - pytorch>=1.4.0
  - rdkit>=2020.03.1.0
  - scikit-learn>=0.22.2.post1
  - scipy>=1.4.1
  - tensorboardX>=2.0
  - torchvision>=0.5.0
  - tqdm>=4.45.0
  - pip:
    - typed-argument-parser>=1.6.1
    - prettytable>=0.7.2